---
clusterName: "es-baz"
nodeGroup: "master"

roles:
  master: "true"
  ingest: "true"
  data: "true"

protocol: http

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
# Uncomment for staging/dev
# esJavaOpts: "-Xmx512m -Xms512m"

# resources:
#   requests:
#     cpu: "100m"
#     memory: "1Gi"
#   limits:
#     cpu: "100m"
#     memory: "1Gi"

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
